name: Release

on:
  push:
    tags:
      - "v*"

env:
  GO_VERSION: 1.17
  CGO_ENABLED: 0

jobs:
  main:
    name: Publish Release
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go mod download
      - run: make release

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "dist/*"
          allowUpdates: true
