name: Tests

on:
  - push

env:
  CGO_ENABLED: 0
  GO_VERSION: 1.17

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go mod download
      - run: make build
      - run: make test
